### ISSUE TITLE
Thinkpad Yoga X1 gen 6 fan speed level

### ISSUE THREAD

**Issue by milansimek** [Shuzhengz/TPFanCtrl2#34]
First of all: This version of the program works perfectly fine on the Thinkpad Yoga X1 gen 6 :) At least for my purpose.

In some cases I want the fan to be on max all the time, when doing some intensive tasks. (Using noise cancelling headphones anyway)

I noticed that setting the fan speed to `7` does not increase the speed much. Value `127` does set the fan speed to max though.

Not sure what the reason is but I wanted to share this here in case it helps anyone.

(Not really a bug, but could be improved in the program probably)

**Comment by Shuzhengz** [comment]
Yeah it is like that because the 0-7 range is intended to be used as the fan levels intended by the manufacture (7 being the highest that the laptop BIOS can go), and to take full advantage of the fan you'll need to enter 0-128 in hex (for example, 128 in hex is 0x80, which is entered as 80).
Thanks for the heads up though, probably something that I should put into README :)
