### ISSUE TITLE
TPFanCtrl2 on X1 Extreme Gen 3

### ISSUE THREAD

**Issue by dharmatech** [Shuzhengz/TPFanCtrl2#5]
Hello,

Some discussion regarding using TPFanCtrl2 on an X1 Extreme Gen 3 here:

https://forums.lenovo.com/t5/ThinkPad-X-Series-Laptops/ThinkPad-X1-Extreme-Gen-3-fans-always-on/m-p/5107024?page=1#5471879

Note the messages 'failed to read TEMP1 byte from EC' in the log:

![image](https://user-images.githubusercontent.com/20816/139598548-cdd60500-6ab5-4053-b43f-c3637746ff68.png)

It never seems to drop to fan level 0 when in smart mode, even if the system load is very low.

If I set it to 0 in manual mode, the fans do indeed spin down. (It reverts to smart mode if the temperature goes up.)

Thanks for TPFanCtrl2!

**Comment by Shuzhengz** [comment]
Hi

The EC issue is a known problem caused by Lenovo's BIOS on some newer devices overriding and blocking the software from reading the EC (embedded controller). I'm still working on fixing this issue and hopefully I can get it into another release. This problem usually happens after the CPU reaches a high tempature and thermal throttles, but it can also happen if the EDP gets throtled and the BIOS kicks in as a safety measure. You can sort of get around this by increasing the max read errors and decreasing the cycle time. You can do that by editing the `TPFanControl.ini` file in the directory using notepad, this will make the software attempt to read from EC faster, and sometimes the BIOS lets it through. You can also solve it by enabling Hyper-V in windows control panel, but Lenovo limits the CPU temperature to 80C in that case, and you lose about 15% of your CPU's performance. 

You can also tune the fan curve in `TPFanControl.ini` (around line 238). I set the curve higher than usual on release to prevent any accidental damage to the CPU if the device is incompatible (untested AMD devices and high TDP workstations), but you can tune the curve lower yourself. For example, you can set it to:

`Level=60 0`
`Level=65 0`
`Level=75 1`
`Level=80 3`
`Level=90 7`

Your CPU will thermal throttle itself (the software does not override the MSR registry) so you don't have to worry about damaging you device, but you will lose performance.

Thank you!

**Comment by dharmatech** [comment]
@Shuzhengz 

> For example, you can set it to:
> 
> `Level=60 0` 
> `Level=65 0` 
> `Level=75 1` 
> `Level=80 3` 
> `Level=90 7`

Thanks for these example settings. I've plugged them in and it seems to be working well.

**Comment by Shuzhengz** [comment]
No problem, glad I can help!

**Comment by dharmatech** [comment]
@Shuzhengz,

Here's a screenshot of TPFanControl and the CPU view inTaskManager on my system at the moment:

![image](https://user-images.githubusercontent.com/20816/139704586-a8e680ad-6346-4192-b93a-1375454e65db.png)

However, if I look underneath the laptop at the fans, the left one is off and the right one is on.

Is it normal for only one fan to be on at a time sometimes?

Is there a way to tell from looking at the TPFanControl GUI that only one fan is on?

**Comment by Shuzhengz** [comment]
Huh that's weird, have you tried restarting the program and see if it fixes the issue?

FYI program actually generates a log file if it's in debug mode (if you build it from source that is), and that's probably going to be more useful than the GUI

But yeah I'll definitely look at his version and see

Thank you!

**Comment by Shuzhengz** [comment]
Cool seems like it's this commit that fixes the issue
https://github.com/nikolasgd/TPFanControl-dual-fan/commit/6ad1259c03a66dd0c7905e6f57e6751865b3c231

**Comment by Shuzhengz** [comment]
cool, try release 2.0.3 Beta

**Comment by dharmatech** [comment]
Interesting comment from Niko here:

https://github.com/nikolasgd/TPFanControl-dual-fan/issues/4

He says TPFanControl stopped working after a BIOS upgrade.

**Comment by dharmatech** [comment]
@Shuzhengz,

It would be awesome if the authors of the various forks of TPFanControl collaborated on the same repository so that we all benefit from the shared knowledge, fixes and features.

Have you considered submitting your patches to Niko's repository?

https://github.com/nikolasgd/TPFanControl-dual-fan

**Comment by Shuzhengz** [comment]
Yeah TPFC would sometimes stop working if the BIOS thermal regulator kicks in on newer Intel CPUs (8th gen and later as far as I know).
You can bypass this by editing the MSR registry but that would risk bricking the computer

**Comment by Shuzhengz** [comment]
> Have you considered submitting your patches to Niko's repository?

Sure, but I'm currently working on other things so maybe later
