### ISSUE TITLE
Possible to manually control just one fan?

### ISSUE THREAD

**Issue by rlpowell** [Shuzhengz/TPFanCtrl2#55]
I'm not sure if this a bug or I'm just holding it wrong, but:

I'm on a P71, which has exactly 2 fans, CPU and GPU (trust me, I've replaced them :D ).  TPFC2 sees two fans, "cpu" and "asp".  The second one is clearly the GPU fan, in as much as the temp goes up when I run a GPU benchmark.  It will sometimes *also* say there's a "gpu" fan, but its temp is 1oC, so, ignoring that.

The problem I'm having is that I want to test if the GPU fan is actually working, so I want to manually set the speed on that second fan, but no matter what I do it seems to only control the CPU fan.

I can't see any way to say *which* fan to control in manual mode.  Is it supposed to control both fans in that mode, or what?

Thanks for any assistance.

**Comment by Shuzhengz** [comment]
Hi, the `cpu`, `asp`, and `gpu` are temperatures that are detected in those respective parts of your system and not fans, the program cannot detect the specific fans your computer has, it can only read the speed of the fans from pre-set addresses in the embedded controller.

The program also cannot control only one of the two fans, because with portio, we can only access the embedded controller, and the way that lenovo implemented it is to have one address control both fans. So yes, manual mode sets both fans to that value. 

There is also a known bug in newer thinkpad models where sometimes one of the two fans will fail to react to the value set because of the BIOS kicking in, and the best workaround we have right now is to keep sending it commands until it works. 

Since your GPU temperature only shows up under high load and reports the wrong value, it seems like it's either something in your system is preventing it from being read, or the sensor is faulty. I would suggest using another program like OpenHardwareMonitor to check
